// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIg3nC2wJoJWrSXLjLXUhvTSt-IbScK78',
    appId: '1:144647808969:web:9233c7152e2d8a59786a18',
    messagingSenderId: '144647808969',
    projectId: 'fir-f02b0',
    authDomain: 'fir-f02b0.firebaseapp.com',
    storageBucket: 'fir-f02b0.firebasestorage.app',
    measurementId: 'G-WDQFQ0MLRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj9Px_EZ1O4HtcTH0wSt_TM4HAazvMaQk',
    appId: '1:144647808969:android:f023bdfa1b4f32d7786a18',
    messagingSenderId: '144647808969',
    projectId: 'fir-f02b0',
    storageBucket: 'fir-f02b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw3Vc-MMGAzLZxoal_X70HRR9IQ7qeOj4',
    appId: '1:144647808969:ios:a503d8677b17e0ab786a18',
    messagingSenderId: '144647808969',
    projectId: 'fir-f02b0',
    storageBucket: 'fir-f02b0.firebasestorage.app',
    iosBundleId: 'com.example.paypal1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw3Vc-MMGAzLZxoal_X70HRR9IQ7qeOj4',
    appId: '1:144647808969:ios:a503d8677b17e0ab786a18',
    messagingSenderId: '144647808969',
    projectId: 'fir-f02b0',
    storageBucket: 'fir-f02b0.firebasestorage.app',
    iosBundleId: 'com.example.paypal1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIg3nC2wJoJWrSXLjLXUhvTSt-IbScK78',
    appId: '1:144647808969:web:1d3f4eeee17b6ece786a18',
    messagingSenderId: '144647808969',
    projectId: 'fir-f02b0',
    authDomain: 'fir-f02b0.firebaseapp.com',
    storageBucket: 'fir-f02b0.firebasestorage.app',
    measurementId: 'G-H8Z4NZSCRH',
  );
}
